<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php
echo $this->tag->form(
    array(
        "partidos/search",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    )
);
?>
<div class="row">
    <div class="col-12">
        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">Buscar</h3>
                <div class="btn-group">
                    <?php echo $this->tag->linkTo(array("partidos/new", "<i class='fa fa-lg fa-plus'></i> Nuevo", "class" => "btn btn-primary")) ?>
                </div>
            </div>
            <div class="tile-body">
                <?php echo $this->getContent() ?>

                <div class="form-group row">
                    <label for="fieldLocal" class="col-sm-2 control-label">LOCAL</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("LOCAL", "type" => "number", "class" => "form-control", "id" => "fieldLocal")) ?>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="fieldVisitante" class="col-sm-2 control-label">VISITANTE</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("VISITANTE", "type" => "number", "class" => "form-control", "id" => "fieldVisitante")) ?>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="fieldFasesId" class="col-sm-2 control-label">FASES Of ID</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("FASES_ID", "type" => "number", "class" => "form-control", "id" => "fieldFasesId")) ?>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="fieldFecha" class="col-sm-2 control-label">FECHA</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("FECHA", "size" => 30, "class" => "form-control", "id" => "fieldFecha")) ?>
                    </div>
                </div>
            </div>
            <div class="tile-footer">
                <?php echo $this->tag->submitButton(array("Buscar", "class" => "btn btn-warning")) ?>
            </div>
        </div>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
