<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<div class="row">
    <div class="col-12">
        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">Resultados</h3>
                <div class="btn-group">
                    <?php echo $this->tag->linkTo(array("partidos/search", "<i class='fa fa-lg fa-backward'></i> Atrás", "class" => "btn btn-primary")) ?>
                    <?php echo $this->tag->linkTo(array("partidos/new", "<i class='fa fa-lg fa-plus'></i> Nuevo", "class" => "btn btn-primary")) ?>
                </div>
            </div>
            <div class="tile-body">
                <?php echo $this->getContent() ?>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
<!--                            <th>ID</th>-->
                            <th>Local</th>
                            <th>Visitante</th>
                            <th>Gloes Local</th>
                            <th>Goles Visita</th>
                            <th>Penales Local</th>
                            <th>Penales Visita</th>
                            <th>Fase</th>
                            <th>Fecha</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($page->items as $partido): ?>
                            <tr>
<!--                                <td>--><?php //echo $partido->PARTIDOS_ID ?><!--</td>-->
                                <td><?php echo $partido->getLocal()->NOMBRE ?></td>
                                <td><?php echo $partido->getVisitante()->NOMBRE ?></td>
                                <td><?php echo $partido->GOLES_LOCAL ?></td>
                                <td><?php echo $partido->GOLES_VISITANTE ?></td>
                                <td><?php echo $partido->PENALES_LOCAL ?></td>
                                <td><?php echo $partido->PENALES_VISITANTE ?></td>
                                <td><?php echo $partido->FASES->NOMBRE ?></td>
                                <td><?php echo $partido->FECHA ?></td>
                                <td><?php echo $this->tag->linkTo(array("partidos/edit/" . $partido->PARTIDOS_ID, "Editar")); ?></td>
                                <td><?php echo $this->tag->linkTo(array("partidos/delete/" . $partido->PARTIDOS_ID, "Eliminar")); ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tile-footer">
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div class="dataTables_info" id="sampleTable_info" role="status" aria-live="polite">
                            <?php echo $page->current, "/", $page->total_pages ?>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-7">
                        <div class="dataTables_paginate paging_simple_numbers" id="sampleTable_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("partidos/search", "Primero", "class" => "page-link")) ?></li>
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("partidos/search?page=" . $page->before, "Anterior", "class" => "page-link")) ?></li>
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("partidos/search?page=" . $page->next, "Siguiente", "class" => "page-link")) ?></li>
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("partidos/search?page=" . $page->last, "Último", "class" => "page-link")) ?></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>