<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("campeonatos/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("campeonatos/new", "Crear ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Buscar result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>NOMBRE</th>
            <th>FECHA Of INI</th>
            <th>FECHA Of FIN</th>
            <th>LOGO</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $campeonato): ?>
            <tr>
                <td><?php echo $campeonato->NOMBRE ?></td>
                <td><?php echo $campeonato->FECHA_INI ?></td>
                <td><?php echo $campeonato->FECHA_FIN ?></td>
                <td><img src="data:image/jpeg;base64,<?php echo base64_encode($campeonato->LOGO) ?>"/></td>
                <td><?php echo $this->tag->linkTo(array("campeonatos/edit/" . $campeonato->CAMPEONATO_ID, "Editar")); ?></td>
                <td><?php echo $this->tag->linkTo(array("campeonatos/delete/" . $campeonato->CAMPEONATO_ID, "Eliminar")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("campeonatos/search", "Primero") ?></li>
                <li><?php echo $this->tag->linkTo("campeonatos/search?page=" . $page->before, "Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("campeonatos/search?page=" . $page->next, "Siguiente") ?></li>
                <li><?php echo $this->tag->linkTo("campeonatos/search?page=" . $page->last, "Último") ?></li>
            </ul>
        </nav>
    </div>
</div>
