<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Buscar equipos
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("equipos/new", "Crear equipos")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "equipos/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldEquiposId" class="col-sm-2 control-label">EQUIPOS Of ID</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("EQUIPOS_ID", "type" => "number", "class" => "form-control", "id" => "fieldEquiposId")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombre" class="col-sm-2 control-label">NOMBRE</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("NOMBRE", "size" => 30, "class" => "form-control", "id" => "fieldNombre")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLogo" class="col-sm-2 control-label">LOGO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("LOGO", "size" => 30, "class" => "form-control", "id" => "fieldLogo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAudUsuario" class="col-sm-2 control-label">AUD Of USUARIO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("AUD_USUARIO", "type" => "number", "class" => "form-control", "id" => "fieldAudUsuario")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAudFecha" class="col-sm-2 control-label">AUD Of FECHA</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("AUD_FECHA", "type" => "number", "class" => "form-control", "id" => "fieldAudFecha")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAudEstado" class="col-sm-2 control-label">AUD Of ESTADO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("AUD_ESTADO", "type" => "number", "class" => "form-control", "id" => "fieldAudEstado")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Buscar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
