<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("equipos", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create equipos
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    array(
        "equipos/create",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "enctype" => "multipart/form-data"
    )
);
?>

<div class="form-group">
    <label for="fieldNombre" class="col-sm-2 control-label">NOMBRE</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("NOMBRE", "size" => 30, "class" => "form-control", "id" => "fieldNombre")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLogo" class="col-sm-2 control-label">LOGO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(array("LOGO", "id" => "fieldLogo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAudEstado" class="col-sm-2 control-label">AUD Of ESTADO</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("AUD_ESTADO", "type" => "number", "class" => "form-control", "id" => "fieldAudEstado")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Guardar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
