<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="row">
    <div class="col-12">

        <?php
        echo $this->tag->form(
            array(
                "equipos/create",
                "enctype"=>"multipart/form-data",
                "class" => "form-horizontal"
            )
        );
        ?>

        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">Nuevo equipo</h3>
                <div class="btn-group">
                    <?php echo $this->tag->linkTo(array("equipos", "<i class='fa fa-lg fa-backward'></i> Atrás", "class" => "btn btn-primary")) ?>
                </div>
            </div>
            <div class="tile-body">
                <?php echo $this->getContent(); ?>

                <div class="form-group row">
                    <label for="fieldNombre" class="col-sm-2 control-label">NOMBRE</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("NOMBRE", "size" => 30, "class" => "form-control", "id" => "fieldNombre")) ?>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="fieldLogo" class="col-sm-2 control-label">LOGO</label>
                    <div class="col-sm-10">
                        <?php echo $this->tag->fileField(array("LOGO", "size" => 30, "class" => "form-control", "id" => "fieldLogo")) ?>
                    </div>
                </div>

            </div>
            <div class="tile-footer">
                <?php echo $this->tag->submitButton(array("Guardar", "class" => "btn btn-warning")) ?>
            </div>
        </div>

        <?php echo $this->tag->endForm(); ?>

    </div>


</div>