<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<div class="row">
    <div class="col-12">

        <?php
        echo $this->tag->form(
            array(
                "equipos/create",
                "enctype" => "multipart/form-data",
                "class" => "form-horizontal"
            )
        );
        ?>

        <div class="tile">
            <div class="tile-title-w-btn">
                <h3 class="title">Nuevo equipo</h3>
                <div class="btn-group">
                    <?php echo $this->tag->linkTo(array("equipos/index", "<i class='fa fa-lg fa-backward'></i> Atrás", "class" => "btn btn-primary")) ?>
                    <?php echo $this->tag->linkTo(array("equipos/new", "<i class='fa fa-lg fa-plus'></i> Nuevo", "class" => "btn btn-primary")) ?>
                </div>
            </div>
            <div class="tile-body">
                <?php echo $this->getContent(); ?>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>EQUIPOS Of ID</th>
                        <th>NOMBRE</th>
                        <th>LOGO</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($page->items as $equipo): ?>
                        <tr>
                            <td><?php echo $equipo->EQUIPOS_ID ?></td>
                            <td><?php echo $equipo->NOMBRE ?></td>
                            <td><img style="max-width: 100px;" class="img-responsive"
                                     src="data:image/jpeg;base64,<?php echo base64_encode($equipo->LOGO) ?>"/></td>
                            <td><?php echo $this->tag->linkTo(array("equipos/edit/" . $equipo->EQUIPOS_ID, "Editar")); ?></td>
                            <td><?php echo $this->tag->linkTo(array("equipos/delete/" . $equipo->EQUIPOS_ID, "Eliminar")); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
            <div class="tile-footer">
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div class="dataTables_info" id="sampleTable_info" role="status" aria-live="polite">
                            <?php echo $page->current, "/", $page->total_pages ?>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-7">
                        <div class="dataTables_paginate paging_simple_numbers" id="sampleTable_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("equipos/search", "Primero", "class" => "page-link")) ?></li>
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("equipos/search?page=" . $page->before, "Anterior", "class" => "page-link")) ?></li>
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("equipos/search?page=" . $page->next, "Siguiente", "class" => "page-link")) ?></li>
                                <li class="paginate_button page-item "><?php echo $this->tag->linkTo(array("equipos/search?page=" . $page->last, "Último", "class" => "page-link")) ?></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php echo $this->tag->endForm(); ?>

    </div>


</div>